"""Auto-ticketing via GitHub Issues (version 2 substrate).

Files one issue per P1/P2 finding (configurable threshold), with an
explainable body: score breakdown, threat intel, attack-path context,
remediation (first-aid + full), SLA + owner labels.

De-dup guard: if an open issue with the same ``[P1]``-prefixed title already
exists, we skip instead of spamming.  Uses ``urllib`` (stdlib) so the Docker
image needs no extra packages.
"""
from __future__ import annotations

import json
import os
import urllib.request
from typing import Any, Dict, List, Optional

from core.models import Finding

API = "https://api.github.com"


class GitHubError(RuntimeError):
    pass


class GitHubIssues:
    def __init__(self, repo: str, token: str, dry_run: bool = False):
        self.repo = repo  # "owner/name"
        self.token = token
        self.dry_run = dry_run

    # ------------------------------------------------------------------ http
    def _request(self, method: str, path: str, body: Optional[Dict] = None) -> Any:
        url = f"{API}{path}"
        data = json.dumps(body).encode() if body is not None else None
        req = urllib.request.Request(url, data=data, method=method)
        req.add_header("Authorization", f"Bearer {self.token}")
        req.add_header("Accept", "application/vnd.github+json")
        req.add_header("User-Agent", "vulnlab-risk-pipeline/1.0")
        if data:
            req.add_header("Content-Type", "application/json")
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                raw = resp.read().decode()
                return json.loads(raw) if raw else {}
        except urllib.error.HTTPError as exc:
            raise GitHubError(f"GitHub {method} {path} -> HTTP {exc.code}: "
                              f"{exc.read().decode()[:300]}")

    def _open_issue_titles(self) -> set:
        titles = set()
        page = 1
        while True:
            data = self._request("GET", f"/repos/{self.repo}/issues?state=open&per_page=100&page={page}")
            if not data:
                break
            titles.update(i.get("title", "") for i in data)
            if len(data) < 100:
                break
            page += 1
        return titles

    # ---------------------------------------------------------------- filing
    def file_issues(self, findings: List[Finding], threshold: float = 60.0,
                    label: str = "security") -> Dict[str, Any]:
        """File one issue per active finding with score >= threshold."""
        stats = {"created": 0, "skipped_duplicate": 0, "below_threshold": 0,
                 "errors": []}
        if not self.token:
            stats["errors"].append("no token configured")
            return stats
        existing = self._open_issue_titles() if not self.dry_run else set()
        for f in findings:
            if f.status != "active":
                continue
            score = f.score or 0
            if score < threshold:
                stats["below_threshold"] += 1
                continue
            title = f"[{f.priority}] {f.title} ({f.product})"
            if title in existing:
                stats["skipped_duplicate"] += 1
                continue
            body = _issue_body(f)
            if self.dry_run:
                stats["created"] += 1
                continue
            try:
                self._request("POST", f"/repos/{self.repo}/issues", {
                    "title": title,
                    "body": body,
                    "labels": [label, f"priority:{f.priority}"],
                })
                stats["created"] += 1
            except GitHubError as exc:
                stats["errors"].append(str(exc))
        return stats


def _issue_body(f: Finding) -> str:
    comps = (f.score_breakdown or {}).get("components", {})
    comp_table = "\n".join(f"| {k} | {v} |" for k, v in sorted(comps.items()))
    remediation = "\n".join(
        f"- **{s.get('kind')}:** {s.get('text', '')}" for s in (f.remediation_suggestions or []))
    return f"""## Risk score: {f.score:.1f}/100 — {f.priority} (SLA {f.sla_hours}h)

**Owner:** {f.owner} · **Product:** {f.product} · **Scanner:** {f.scanner}
**CVE:** {f.cve or '-'} · **CWE:** {f.cwe or '-'} · **Endpoint:** {f.endpoint or '-'}

### Score breakdown
| factor | points |
|---|---|
{comp_table}

### Threat intel
- EPSS: {f.epss_score or 0:.4f} (percentile {f.epss_percentile or 0:.3f}, trend {f.epss_trend or 0:+.4f}/7d)
- CISA KEV: {'YES (' + (f.kev_date or '') + ')' if f.kev else 'no'}
- Public exploit: {'yes (' + (f.exploit_source or '?') + ')' if f.exploit_available else 'no'}
- Escalation potential: {f.escalation_potential or 0.0:.2f}

### Description
{f.description or 'n/a'}

### Remediation
{remediation or 'No guidance provided.'}

---
_Generated by the risk-pipeline v2 (score {f.score:.1f}, auto-ticket threshold)._
"""


def write_tickets_md(findings: List[Finding], path: str, threshold: float = 60.0) -> int:
    """Local ticket file (works offline; also used by the CI artifact)."""
    lines = ["# Auto-generated tickets (ticket-ready action list)",
             "", f"Threshold: score >= {threshold}", ""]
    count = 0
    for f in findings:
        if f.status != "active" or (f.score or 0) < threshold:
            continue
        count += 1
        lines.append(f"## {count}. [{f.priority}] {f.title}")
        lines.append(f"- Score **{f.score:.1f}** · Owner **{f.owner}** · SLA {f.sla_hours}h")
        lines.append(f"- Product {f.product} · Scanner {f.scanner} · CVE {f.cve or '-'} · CWE {f.cwe or '-'}")
        lines.append(f"- Endpoint: {f.endpoint or '-'}")
        lines.append("")
    lines.append(f"_{count} ticket(s) ready._")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    return count
